name: CI
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: gradle
      - name: run test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: build
      - name: Generate Coveralls Test Report
        run: ./gradlew jacocoTestReport coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
          CI_NAME: Github Actions
          CI_BRANCH: ${{github.ref}}
          CI_PULL_REQUEST: ${{github.event.pull_request.html_url}}
          